### ISSUE TITLE
Should write newlines at the end of files

### ISSUE THREAD

**Issue by paulkernfeld** [jostylr/literate-programming#19]
I think it's generally considered good practice to add newlines to the end of files, especially since some tools complain if they are not present. [This StackOverflow question](http://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline) says that ending files w/ a newline is part of the POSIX standard.

**Comment by jostylr** [comment]
Yes, it should add a newline. In the more recent version of this tool, at [litpro](https://github.com/jostylr/litpro)  this should be adding newlines. Since I am intending to replace this with litpro, I recommend trying that. It is much more powerful but should be mostly compatible. See [litpro-lib](https://github.com/jostylr/literate-programming-lib) for more documentation on what it can do. 

Let me know if that works out for you. Otherwise, I'll see about adding the newline behavior to this. Would prefer not to modify this version at all at this point.

**Comment by paulkernfeld** [comment]
Awesome, switching to litpro fixes this for me, thanks! Can I add a note to the README of this library that it's no longer supported and users should switch to litpro?

**Comment by jostylr** [comment]
Note added; glad litpro worked for you. I intend to put litpro+batteries here, but it has taken a long time to get around to doing that.
